development:
  adapter: postgresql
  encoding: utf8
  database: fantasy_financial_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: fantasy_financial_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: fantasy_financial_production
  pool: 5